/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export declare namespace Transactions {
  export type TransferStructStruct = {
    sender: PromiseOrValue<string>;
    receiver: PromiseOrValue<string>;
    amount: PromiseOrValue<BigNumberish>;
    message: PromiseOrValue<string>;
    timestamp: PromiseOrValue<BigNumberish>;
    keyword: PromiseOrValue<string>;
  };

  export type TransferStructStructOutput = [
    string,
    string,
    BigNumber,
    string,
    BigNumber,
    string
  ] & {
    sender: string;
    receiver: string;
    amount: BigNumber;
    message: string;
    timestamp: BigNumber;
    keyword: string;
  };
}

export interface TransactionsInterface extends utils.Interface {
  functions: {
    "addToBlock(address,uint256,string,string)": FunctionFragment;
    "getAllTransactions()": FunctionFragment;
    "getTransactionCount()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addToBlock"
      | "getAllTransactions"
      | "getTransactionCount"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addToBlock",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllTransactions",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTransactionCount",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "addToBlock", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllTransactions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTransactionCount",
    data: BytesLike
  ): Result;

  events: {
    "Transfer(address,address,uint256,string,uint256,string)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Transfer"): EventFragment;
}

export interface TransferEventObject {
  sender: string;
  receiver: string;
  amount: BigNumber;
  message: string;
  timestamp: BigNumber;
  keyword: string;
}
export type TransferEvent = TypedEvent<
  [string, string, BigNumber, string, BigNumber, string],
  TransferEventObject
>;

export type TransferEventFilter = TypedEventFilter<TransferEvent>;

export interface Transactions extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: TransactionsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addToBlock(
      receiver: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      message: PromiseOrValue<string>,
      keyword: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getAllTransactions(
      overrides?: CallOverrides
    ): Promise<[Transactions.TransferStructStructOutput[]]>;

    getTransactionCount(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  addToBlock(
    receiver: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    message: PromiseOrValue<string>,
    keyword: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getAllTransactions(
    overrides?: CallOverrides
  ): Promise<Transactions.TransferStructStructOutput[]>;

  getTransactionCount(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    addToBlock(
      receiver: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      message: PromiseOrValue<string>,
      keyword: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    getAllTransactions(
      overrides?: CallOverrides
    ): Promise<Transactions.TransferStructStructOutput[]>;

    getTransactionCount(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {
    "Transfer(address,address,uint256,string,uint256,string)"(
      sender?: null,
      receiver?: null,
      amount?: null,
      message?: null,
      timestamp?: null,
      keyword?: null
    ): TransferEventFilter;
    Transfer(
      sender?: null,
      receiver?: null,
      amount?: null,
      message?: null,
      timestamp?: null,
      keyword?: null
    ): TransferEventFilter;
  };

  estimateGas: {
    addToBlock(
      receiver: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      message: PromiseOrValue<string>,
      keyword: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getAllTransactions(overrides?: CallOverrides): Promise<BigNumber>;

    getTransactionCount(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    addToBlock(
      receiver: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      message: PromiseOrValue<string>,
      keyword: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getAllTransactions(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTransactionCount(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
